From python:3.10

ADD main.py .

RUN pip install scikit-learn
RUN pip install matplotlib
RUN pip install numpy
RUN pip install opencv-python

CMD ["python3", "./main.py"]
#CMD ["python3", "test_img.py"]